apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../vllm
  - resource-claim-template-rdma.yaml

patches:
  - target:
      kind: Deployment
      name: decode
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: ib,rc,ze_copy
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: UCX_MEMTYPE_CACHE
          value: "0"
      - op: add
        path: /spec/template/spec/containers/0/resources/claims/-
        value:
          name: rdma-claim
      - op: add
        path: /spec/template/spec/resourceClaims/-
        value:
          name: rdma-claim
          resourceClaimTemplateName: intel-rdma-claim-template
  - target:
      kind: Deployment
      name: prefill
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: ib,rc,ze_copy
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: UCX_MEMTYPE_CACHE
          value: "0"
      - op: add
        path: /spec/template/spec/containers/0/resources/claims/-
        value:
          name: rdma-claim
      - op: add
        path: /spec/template/spec/resourceClaims/-
        value:
          name: rdma-claim
          resourceClaimTemplateName: intel-rdma-claim-template