apiVersion: v1
kind: Pod
metadata:
  name: xpu-docker-run-equivalent
spec:
  hostNetwork: true
  hostIPC: true
  dnsPolicy: ClusterFirstWithHostNet
  containers:
    - name: modelserver
      image: vllm-xpu-env:latest
      tty: true
      stdin: true
      securityContext:
        privileged: true
      env:
        - name: HF_ENDPOINT
          value: https://hf-mirror.com
        - name: no_proxy
          value: intel.com,.intel.com,localhost,127.0.0.1
        - name: http_proxy
          value: http://proxy-shz.intel.com:912
        - name: https_proxy
          value: http://proxy-shz.intel.com:912
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: llm-d-hf-token
              key: HF_TOKEN
      volumeMounts:
        - name: dev-dri
          mountPath: /dev/dri
        - name: dev-dri-by-path
          mountPath: /dev/dri/by-path
  volumes:
    - name: dev-dri
      hostPath:
        path: /dev/dri
    - name: dev-dri-by-path
      hostPath:
        path: /dev/dri/by-path
