apiVersion: apps/v1
kind: Deployment
metadata:
  name: decode
spec:
  replicas: 1
  template:
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      securityContext:
        fsGroup: 107
        supplementalGroups:
          - 107
      containers:
        - name: modelserver
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c"]
          args:
            - |
              source /opt/intel/oneapi/setvars.sh --force >/dev/null 2>&1 || source /opt/intel/oneapi/setvars.sh >/dev/null 2>&1 || true
              exec vllm serve \
                Qwen/Qwen3-8B \
                --dtype bfloat16 \
                --tensor-parallel-size=1 \
                --gpu-memory-utilization 0.75 \
                --max-num-seq 128 \
                --uvicorn-log-level warning
          env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: llm-d-hf-token
                  key: HF_TOKEN
            - name: USER
              value: llm-d
            - name: VLLM_TARGET_DEVICE
              value: xpu
            - name: VLLM_USE_V1
              value: "1"
            - name: TORCH_LLM_ALLREDUCE
              value: "1"
            - name: VLLM_WORKER_MULTIPROC_METHOD
              value: "spawn"
            - name: VLLM_LOGGING_LEVEL
              value: "DEBUG"
          resources:
            limits:
              cpu: '8'
              memory: 30Gi
            requests:
              cpu: '8'
              memory: 30Gi
            claims:
              - name: xpu-claim
          volumeMounts:
            - mountPath: /dev/dri
              name: dev-dri
            - mountPath: /dev/dri/by-path
              name: dev-dri-by-path
            - mountPath: /dev/shm
              name: shm
            - mountPath: /.cache
              name: torch-compile-cache
            - mountPath: /.triton
              name: triton-cache
            - mountPath: /.config
              name: vllm-config
          startupProbe:
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 120
          livenessProbe:
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
      restartPolicy: Always
      resourceClaims:
        - name: xpu-claim
          resourceClaimTemplateName: xpu-claim
      enableServiceLinks: false
      terminationGracePeriodSeconds: 130
      volumes:
        - name: dev-dri
          hostPath:
            path: /dev/dri
        - name: dev-dri-by-path
          hostPath:
            path: /dev/dri/by-path
        - name: data
          emptyDir: {}
        - name: shm
          emptyDir:
            medium: Memory
        - name: torch-compile-cache
          emptyDir: {}
        - name: triton-cache
          emptyDir: {}
        - name: vllm-config
          emptyDir: {}
